pragma circom 2.1.6;

include "../node_modules/poseidon-bls12381-circom/circuits/poseidon255.circom";
include "../node_modules/circomlib/circuits/bitify.circom";
include "../node_modules/circomlib/circuits/comparators.circom";
include "../node_modules/circomlib/circuits/mux1.circom";

// ============================================================================
// Poseidon2: 2-input Poseidon BLS12-381 hash
// ============================================================================
//
// Matches the on-chain pool's expectation: H(a, b) using BLS12-381 scalar
// field. The same template is used by every component in this directory.

template Poseidon2() {
    signal input a;
    signal input b;
    signal output out;

    component h = Poseidon255(2);
    h.in[0] <== a;
    h.in[1] <== b;
    out <== h.out;
}

// ============================================================================
// MerkleProof: proves `root = MerkleRoot(leaf, leafIndex, path)`
// ============================================================================
//
// `levels` is the tree depth (20 for the final circuits). At each level we hash
// the running node with the appropriate sibling, picking left/right by the bit
// at the matching position of `leafIndex`.

template MerkleProof(levels) {
    signal input leaf;
    signal input root;
    signal input pathElements[levels];
    signal input pathIndices[levels];

    component hashers[levels];
    signal hashes[levels + 1];

    hashes[0] <== leaf;

    for (var i = 0; i < levels; i++) {
        hashers[i] = Poseidon2();

        // Constrain pathIndices[i] to be a bit.
        pathIndices[i] * (1 - pathIndices[i]) === 0;

        // mux: if bit = 0 -> (left = current, right = sibling)
        //       if bit = 1 -> (left = sibling, right = current)
        hashers[i].a <== pathIndices[i] * (pathElements[i] - hashes[i]) + hashes[i];
        hashers[i].b <== (1 - pathIndices[i]) * (pathElements[i] - hashes[i]) + hashes[i];

        hashes[i + 1] <== hashers[i].out;
    }

    root === hashes[levels];
}

// ============================================================================
// MerkleInsertProof: proves `newRoot = Insert(oldRoot, leaf, leafIndex)`
// ============================================================================
//
// Given the current tree (oldRoot) and the index where the new leaf goes,
// this enforces:
//   - The path under leafIndex currently hashes to oldRoot when the leaf
//     position holds the empty-subtree constant (ZERO_VALUES[level]).
//   - After replacing that empty-subtree leaf with `leaf`, the same path
//     hashes to newRoot.
//
// Both checks share the same path of siblings, so the proof commits to:
//   - the path elements (siblings)
//   - the leaf index (path indices)
//   - the empty-subtree constants used at each level (witness `zeros[]`)
//
// The witness is generated by the client from its local view of the tree.

template MerkleInsertProof(levels) {
    // Public
    signal input oldRoot;
    signal input newRoot;
    signal input leaf;
    signal input leafIndex;       // 0 .. 2^levels - 1

    // Witness (private)
    signal input pathElements[levels];      // siblings under leafIndex (same for old/new)
    signal input zeros[levels];             // empty-subtree constants (same for old/new)

    // Defense-in-depth: pin the witness-supplied `zeros[]` to the canonical
    // Poseidon BLS12-381 empty-subtree chain, baked here as compile-time
    // constants. Without this pinning, soundness would depend entirely on
    // the pool contract's `oldRoot == currentRoot` + `leafIndex == nextIndex`
    // checks; if a downstream refactor relaxes either, a malicious prover
    // could overwrite occupied leaves.
    //
    // Cost: 20 equality constraints (one per level) instead of recomputing
    // the chain inside the circuit, which would cost ~6,500 constraints.
    //
    // The values are generated by `circuits/scripts/compute-zeros.js`. CI
    // gate `check-zeros.js` reruns that script every build and fails if any
    // value drifts from what is hardcoded below. Poseidon(ZEROS[19], ZEROS[19])
    // also matches `EMPTY_TREE_ROOT` in `contracts/constants.tolk`.
    //
    // This template assumes `levels == 20`. The values below MUST be
    // regenerated if `MERKLE_TREE_DEPTH` ever changes.
    var ZEROS[20] = [
        0x0000000000000000000000000000000000000000000000000000000000000000,
        0x720772992425c4618eaf8a7ff4b6ad5333a76fe17dd3624e2329a57dfaaa505e,
        0x4a631147afb4978b80f7d8c40526ca2815e3587a088011ed24d11215d549fe88,
        0x3d80cb9c131f7c003cfb82ad7580b88420c216204962cf952256dc785ff68839,
        0x571de3db51ffb4a0181a0b56a613726377dbd093265c4c3800f6c4595079c5c8,
        0x3710eeae180bad05ae19ce0bcc836ad2dee7fb9835a00f2ac4675466a0eef347,
        0x30de0f3432e12933f0fe438a960eeb42855c7d666a378b2ebc43aff37c52d053,
        0x3f6004a2a18568e13c38e4cafe62cb89f10142516f1c217617885d33a54e4dff,
        0x0f014e0c4bc64f4b27d439c1d94837f99e4d9df3a4c9a062c5294c1a0842eea1,
        0x70bf7834ccd244e48fa857920f61b6202cd1dcf49e3017164c82c30ff56cec99,
        0x1ec4b50cea868b8ae6ac178b403ed3bcc9a2340e99e4ac0cff7ae09c51d4ca0b,
        0x2950a7758b1c3583fa951dd305922403108abe2c0c41bb3f667fae3c53f8ac74,
        0x0ce3a78a0131c84050bbe2205642f9e176ffe98488dbddb19336b987420f3bde,
        0x7035643ab6675732ddfe5eb93315c64468e118c7f3b6e0b31a0f9f9d9fc09582,
        0x027aff7829dcd05a1c4881c4e2808cd6bfe601716d4c27b3b835c5210abdadca,
        0x50442ae1bcc1b63aad3834fbdc9318b2c19ab8b1f1bcc393d2099c9fa75b2cf8,
        0x4e6ae32bdee5ff180cb38df7efa2db2cfa6675a3d850c1fdd1d4fd2f52cd4a78,
        0x3746e46d4a05178d2372587ff8efda086097080bdd6e164abd03acfacca2d3fe,
        0x18114db248d9db24edfc1cc535ca953a253c7337a3efb73fb6b0b4751bce8fb5,
        0x5edfe2b717576a55ff8296f83ab58229e0a8349617f2207e64e78daa56d09442
    ];
    for (var i = 0; i < levels; i++) {
        zeros[i] === ZEROS[i];
    }

    // Decompose leafIndex into bits (LSB first): these are the pathIndices.
    component bits = Num2Bits(levels);
    bits.in <== leafIndex;

    // Old: leaf position has the empty-subtree constant zeros[0]
    component oldProof = MerkleProof(levels);
    oldProof.leaf <== zeros[0];
    oldProof.root <== oldRoot;
    for (var i = 0; i < levels; i++) {
        oldProof.pathElements[i] <== pathElements[i];
        oldProof.pathIndices[i]  <== bits.out[i];
    }

    // New: same path, leaf position now holds `leaf`.
    component newProof = MerkleProof(levels);
    newProof.leaf <== leaf;
    newProof.root <== newRoot;
    for (var i = 0; i < levels; i++) {
        newProof.pathElements[i] <== pathElements[i];
        newProof.pathIndices[i]  <== bits.out[i];
    }

    // Anti-optimization: bind public inputs so the compiler does not drop them.
    signal s1 <== oldRoot * oldRoot;
    signal s2 <== newRoot * newRoot;
    signal s3 <== leaf * leaf;
    signal s4 <== leafIndex * leafIndex;
}

// ============================================================================
// CommitmentHasher: derives commitment and nullifierHash from (nullifier, secret)
// ============================================================================
//
// The pool stores `commitment = Poseidon(nullifier, secret)` as the leaf.
// At withdrawal time, `nullifierHash = Poseidon(nullifier, 0)` is revealed
// to prevent double-spend without exposing `secret`.

template CommitmentHasher() {
    signal input nullifier;
    signal input secret;
    signal output commitment;
    signal output nullifierHash;

    component cHasher = Poseidon2();
    cHasher.a <== nullifier;
    cHasher.b <== secret;
    commitment <== cHasher.out;

    component nHasher = Poseidon2();
    nHasher.a <== nullifier;
    nHasher.b <== 0;
    nullifierHash <== nHasher.out;
}
