#!/usr/bin/env node
//
// vk-to-tolk.js: generate Tolk constants from a snarkjs Groth16 BLS12-381 VK.
//
// Usage:
//   node scripts/vk-to-tolk.js <vk.json> <CIRCUIT_TAG>
//
// Produces a file with functions named vk<Tag>Alpha1, vk<Tag>Beta2,
// vk<Tag>Gamma2, vk<Tag>Delta2, vk<Tag>Ic(i) that the existing verifier-*.tolk
// can directly call (replacing the stub returning zero slices).

import { readFileSync } from "node:fs";
import { g1ToChunks, g2ToChunks } from "./bls-encode.js";

const [, , vkPath, tag] = process.argv;
if (!vkPath || !tag) {
    console.error("Usage: vk-to-tolk.js <vk.json> <CIRCUIT_TAG>");
    process.exit(2);
}

const vk = JSON.parse(readFileSync(vkPath, "utf8"));
const tagLower = tag.charAt(0).toUpperCase() + tag.slice(1).toLowerCase();

function emitG1Function(name, point) {
    const chunks = g1ToChunks(point);
    const lines = [
        "@pure",
        `fun ${name}(): slice {`,
        `    return beginCell()`,
    ];
    for (let i = 0; i < 8; i++) {
        lines.push(`        .storeUint(${chunks[i]}, 48)`);
    }
    lines.push(`        .endCell()`);
    lines.push(`        .beginParse();`);
    lines.push(`}`);
    return lines.join("\n");
}

function emitG2Function(name, point) {
    const chunks = g2ToChunks(point);
    const lines = [
        "@pure",
        `fun ${name}(): slice {`,
        `    return beginCell()`,
    ];
    for (let i = 0; i < 8; i++) {
        lines.push(`        .storeUint(${chunks[i]}, 96)`);
    }
    lines.push(`        .endCell()`);
    lines.push(`        .beginParse();`);
    lines.push(`}`);
    return lines.join("\n");
}

function emitIcFunction(prefix, IC) {
    if (IC.length === 0) {
        throw new Error("verification key must contain at least one IC point");
    }
    const lines = [
        `@pure`,
        `fun ${prefix}Ic(i: int): slice {`,
        `    // Auto-generated from ${vkPath}`,
    ];
    for (let idx = 0; idx < IC.length - 1; idx++) {
        const chunks = g1ToChunks(IC[idx]);
        lines.push(`    if (i == ${idx}) {`);
        lines.push(`        return beginCell()`);
        for (let i = 0; i < 8; i++) {
            lines.push(`            .storeUint(${chunks[i]}, 48)`);
        }
        lines.push(`            .endCell()`);
        lines.push(`            .beginParse();`);
        lines.push(`    }`);
    }
    const lastChunks = g1ToChunks(IC[IC.length - 1]);
    lines.push(`    // Verifier callers use the fixed circuit arity, so the last IC`);
    lines.push(`    // point is the exhaustive final case.`);
    lines.push(`    return beginCell()`);
    for (let i = 0; i < 8; i++) {
        lines.push(`        .storeUint(${lastChunks[i]}, 48)`);
    }
    lines.push(`        .endCell()`);
    lines.push(`        .beginParse();`);
    lines.push(`}`);
    return lines.join("\n");
}

const out = [
    `// Auto-generated by scripts/vk-to-tolk.js`,
    `// Source: ${vkPath}`,
    `// Circuit tag: ${tag}`,
    `// DO NOT EDIT: re-run the script after each ceremony pass.`,
    ``,
    emitG1Function(`vk${tagLower}Alpha1`, vk.vk_alpha_1),
    ``,
    emitG2Function(`vk${tagLower}Beta2`, vk.vk_beta_2),
    ``,
    emitG2Function(`vk${tagLower}Gamma2`, vk.vk_gamma_2),
    ``,
    emitG2Function(`vk${tagLower}Delta2`, vk.vk_delta_2),
    ``,
    emitIcFunction(`vk${tagLower}`, vk.IC),
];

console.log(out.join("\n"));
